### ISSUE TITLE
how can i get Japanese name?

### ISSUE THREAD

**Issue by a-club113** [pwnblog/enka.py#3]
I changed "await client.load_lang()" in  [this code](https://github.com/pwnless/enka.py#usage) section to "await client.load_lang(lang='jp') and executed the code, but I could not get it in Japanese Properly.
How can i get it in Japanese?

i use python 3.12.1 in Windows10, VS Code 1.85.1, and ver. 1.2.1 enka.py.

**Comment by pwnless** [comment]
Add ```client.lang='jp'``` before ```await client.load_lang('jp')```

Probably I should change this in future, let load_lang set the self.lang automatically

**Comment by a-club113** [comment]
> Add `client.lang='jp'` before `await client.load_lang('jp')`
> 
> Probably I should change this in future, let load_lang set the self.lang automatically

oh, thanks!
it worked!
